### ISSUE TITLE
docker compose versions?

### ISSUE THREAD

**Issue by hcooper** [RopeWiki/app#35]
The docs state:

> Install legacy/v1 docker-compose...
> verify installation with `docker-compose --version`; result should be 1.29.2 or similar, not 2.x.x

However I've had no problem using modern inbuilt docker-compose  v2.17.3 (aka `docker compose...`).

The only caviet to that is this line of code: https://github.com/RopeWiki/app/blob/93d285648899edd1db9e0e70e848fd13b13dcdd5/deploy_tool.py#L42

The compose `-p` flag now produces containers with `-` not `_` in the names. This only seems to affect the sql restore commands.

If there is more complicated problems I'm missing, the `COMPOSE_COMPATIBILITY ` flag can be set to revert the new version to old behavior: https://stackoverflow.com/a/69519102/142270

**Comment by llamafilm** [comment]
Hi.  I'm new to this project, I just set it up locally to get my feet wet.  I also noticed this issue causes `deploy_tool.py` to fail

**Comment by llamafilm** [comment]
Hi, I'm new to this project.  I'm interested in helping, so I just set it up locally to get my feet wet.  I found this issue right away because it causes the deployment to fail here:
https://github.com/RopeWiki/app/blob/fbe903b8782f2648e6642d0234462481428aca62/deploy_tool.py#L313

Underscore is actually not allowed in DNS names, that's why v2 made this change.  I made a commit to replace all underscores in hostnames with hyphens, including container names even though that's not strictly necessary.
e6992068d7a3cd318e6f8dd8029d42400b363a58

**Comment by BenjaminPelletier** [comment]
Strictly speaking, it's [hostnames rather than DNS names](https://stackoverflow.com/a/2183140/651139) that aren't allowed to have underscores, and I'm generally happy to fix/have fixed the hostnames in, e.g., the docker compose YAML.  But, could you elaborate on how the deployment fails?  We have 3 developers and the production deployment who successfully use the repo as it is currently, so failing due to an invalid hostname seems surprising and makes me suspicious that the underscore in hostname issue may not actually be your root problem.

PRs are always welcome in any case though :)  There are at least 5 things that may currently have underscores in them: hostnames, container names, service names, deployment names, and deployment configuration names.  It definitely seems reasonable to make sure hostnames don't have underscores, and it seems reasonable to make sure container names easily/obviously reveal their hostnames (e.g., container name = [deployment name]-[hostname] or [deployment name]_[hostname]).

docker-compose v1 takes extra effort to install now so I still support the intent of this issue, which is to replace docker-compose v1 with the v2 compose plugin for docker (which happens to concatenate with dashes).

**Comment by llamafilm** [comment]
Ah, you're right!  I was just assuming DNS name follows hostname.

To clarify, the build only fails when I use compose v2.  I guess your team doesn't notice it because you use v1?
```
% python3 deploy_tool.py local create_db
2023-06-26T09:15:54.513905 Deleting/cleaning up any existing database...
2023-06-26T09:15:54.514133   RUN git log -n 1
2023-06-26T09:15:54.534875   RUN git status
2023-06-26T09:15:54.548230   SCRIPT docker-compose -p local stop ropewiki_db
2023-06-26T09:15:54.548256   RUN sh /Users/ebalsley/source/ropewiki/app/docker_compose_command.sh && rm /Users/ebalsley/source/ropewiki/app/docker_compose_command.sh
2023-06-26T09:15:54.787903   SCRIPT docker-compose -p local rm -v -f ropewiki_db
2023-06-26T09:15:54.787945   RUN sh /Users/ebalsley/source/ropewiki/app/docker_compose_command.sh && rm /Users/ebalsley/source/ropewiki/app/docker_compose_command.sh
[]
No stopped containers
2023-06-26T09:15:54.882906   RUN docker volume ls
2023-06-26T09:15:54.933723   SCRIPT docker-compose -p local up -d ropewiki_db ropewiki_backup_manager
2023-06-26T09:15:54.933768   RUN sh /Users/ebalsley/source/ropewiki/app/docker_compose_command.sh && rm /Users/ebalsley/source/ropewiki/app/docker_compose_command.sh
[+] Running 5/5
 ✔ Network local_default                      C...                         0.1s 
 ✔ Volume "ropewiki_proxy_certs"              Created                      0.0s 
 ✔ Volume "ropewiki_database_storage"         Created                      0.0s 
 ✔ Container local-ropewiki_db-1              Started                      0.4s 
 ✔ Container local-ropewiki_backup_manager-1  Started                      0.7s 
2023-06-26T09:15:55.811256 >> Waiting for MySQL database to initialize...
2023-06-26T09:16:00.814939   RUN docker inspect --format "{{.State.Status}}" local_ropewiki_db_1

Error: No such object: local_ropewiki_db_1

ERROR: Return code 1
```

**Comment by hcooper** [comment]
This GH issue is more standardizing developer work flow than fixing a
technical issue.

The actual question (for Ben to answer) is why the docs and code require
v1. I use v2 happily with tiny changes about _ and -.

**Comment by BenjaminPelletier** [comment]
The container names for the [database](https://github.com/RopeWiki/app/blob/fbe903b8782f2648e6642d0234462481428aca62/deploy_tool.py#L43) and [backup manager](https://github.com/RopeWiki/app/blob/fbe903b8782f2648e6642d0234462481428aca62/deploy_tool.py#L51) are hardcoded in deploy_tool.py to be constructed in the way that docker-compose v1 constructs container names -- docker compose v2 constructs container names with dashes and therefore someone using docker compose v2 should* experience exactly the problem in @llamafilm's logs above when attempting to execute a deploy_tool command that involves the database or backup manager containers.

*should = "what happens now", not "what should happen in an ideal world", which is what we'll fix with this issue (shortly) :)
