### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by BenjaminPelletier** [RopeWiki/app#42]
There are at least two pages involving "bobcat": [Bobcat](https://ropewiki.com/Bobcat) and [Bobcat Canyon](https://ropewiki.com/Bobcat_Canyon).  However, typing "bobcat" into the search bar produces no quick results:

![image](https://github.com/RopeWiki/app/assets/11224086/0353572c-2eef-467c-8dd3-7c8b571874d4)

And, searching for "bobcat" produces no results:

![image](https://github.com/RopeWiki/app/assets/11224086/77872eaf-f1a7-4b80-996e-0cf02ee6084c)

**Comment by hcooper** [comment]
The issue is that sphinx isn't starting when the container starts.  Works fine if you manually run:

```
searchd --config /etc/sphinxsearch/sphinx.conf >> /var/log/sphinxsearch/sphinx-startup.log 2>&1
```

These are logs I've found so far:

```
[Mon Jun  5 04:09:15.408 2023] [56] using config file '/etc/sphinxsearch/sphinx.conf'...
Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

WARNING: key 'sql_query_info' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'charset_type' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'max_matches' was permanently removed from Sphinx configuration. Refer to documentation for details.
listening on 127.0.0.1:9312
Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

WARNING: key 'sql_query_info' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'charset_type' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'max_matches' was permanently removed from Sphinx configuration. Refer to documentation for details.
precaching index 'wiki_main'
WARNING: index 'wiki_main': preload: failed to open /var/data/sphinx/wiki_main.sph: No such file or directory; NOT SERVING
precaching index 'wiki_incremental'
WARNING: index 'wiki_incremental': preload: failed to open /var/data/sphinx/wiki_incremental.sph: No such file or directory; NOT SERVING
FATAL: no valid indexes to serve
Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

WARNING: key 'sql_query_info' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'charset_type' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'max_matches' was permanently removed from Sphinx configuration. Refer to documentation for details.
```

**Comment by catware2** [comment]
This is because Sphinx isn't starting. There are two steps to starting Sphinx:
a) run the indexer to create the index files
b) start the searchd daemon to field search requests

Then periodically do this (currently every 30 mins):
c) run the indexer with the --rotate option to update with new results

a) and b) are set in the `system_start.sh` file, and c) is set in the` sphinx.cron` job.

The specific error is that searchd can't find the two files output by the indexer -- `wiki_main.sph` and `wiki_incremental.sph`. However as Coops noted, entering the command to start searchd at some point in the future after system boot, and it works correctly.

I have not seen this issue before in dev. To diagnose, we should:
1) restart the prod server (preferably from a new image build) and see if searchd fails to start
2) if it failed, then check in the `/var/data/sphinx` folder to see if the two files are there or not. This should be done right after the system boots, and definitely before the `indexer --rotate` command is run which happens via the cron job on the half hour.

The other warnings seen in the logs (also seen in the log snippet that Coops posted above) are due to deprecated settings -- I have a branch to remove these named `sphinx_fixes`.

**Comment by hcooper** [comment]
https://github.com/RopeWiki/app/pull/54 is hack to resolve this.
